Update bindings to raylib 4.0.0 and raygui 3.0
tjammer/raylib-ocaml pull request #20
Opened 2021-11-11 22:34 UTC by Willenbrink

Hey!
This PR updates the bindings for both raylib and raygui to their latest releases.
To update the bindings I mainly deleted removed functions and renamed stuff. Nothing too interesting. I've also added some additional accessors for Color, Matrix, Shader and ShaderLoc.

2021-11-13 12:16 UTC, tjammer commented
Nice, thanks! I'm a bit busy this weekend but will check the PR within the week

2021-11-18 14:01 UTC, tjammer requested changes
Looks good to me except for my two comments. I will go over the other PR once this is merged :)

2021-11-21 23:49 UTC, Willenbrink commented on src/raylib/raylib.mli
> +  val t : t Ctypes.typ
I used it for instanced rendering which requires a carray/cptr of matrices. I guess it's not strictly necessary with the workaround of #18 but I don't necessarily agree with removing it from the interface. Why not instead expose the ctyp for every type (or at least every type that occurs as a cptr argument in a raylib function)? I ran into a similar issue with ShaderLoc.t = int not being exposed when writing a shader.

2021-11-21 23:55 UTC, Willenbrink commented on src/raylib/raylib.mli
> +  Vector3.t ->
Oops, thanks for pointing that out

2021-11-22 11:20 UTC, tjammer commented on src/raylib/raylib.mli
> +  val t : t Ctypes.typ
Yes, you're right. It's either that or expose the whole Ctypes type and get rid of the ctyp wrapper.

2021-11-22 11:21 UTC, merged